services:
  tflux.1:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    hostname: 'tflux.1'
    ports:
      - '9000:1606'
      - '9001:1607'
    environment:
      TASKFLUX_CLUSTER_PEERS: 'tflux.1:5000 tflux.2:5000 tflux.3:5000'
      TASKFLUX_CLUSTER_NODE_ID: 0
      TASKFLUX_CLUSTER_LISTEN_PORT: 5000
      TASKFLUX_CLUSTER_LISTEN_HOST: tflux.1
      TASKFLUX_CLUSTER_DATA_DIRECTORY: /var/lib/tflux
      TASKFLUX_HTTP_LISTEN_ADDRESS: 'tflux.1:1606'
      TASKFLUX_GRPC_LISTEN_ADDRESS: 'tflux.1:1607'
      TASKFLUX_TCP_ADAPTER_LISTEN_PORT: 2602
      TASKFLUX_LOG_FILE_SOFT_LIMIT: '33554432'
      TASKFLUX_LOG_FILE_HARD_LIMIT: '67108864'
      TASKFLUX_SNAPSHOT_SNAPSHOT_CREATION_SEGMENTS_THRESHOLD: '5'
    volumes:
      - tflux.1.volume:/var/lib/tflux
    networks:
      - taskflux-network
      
  tflux.2:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    hostname: 'tflux.2'
    ports:
      - '9002:1606'
      - '9003:1607'
    environment:
      TASKFLUX_CLUSTER_PEERS: 'tflux.1:5000 tflux.2:5000 tflux.3:5000'
      TASKFLUX_CLUSTER_NODE_ID: 1
      TASKFLUX_CLUSTER_LISTEN_PORT: 5000
      TASKFLUX_CLUSTER_LISTEN_HOST: tflux.2
      TASKFLUX_CLUSTER_DATA_DIRECTORY: /var/lib/tflux
      TASKFLUX_HTTP_LISTEN_ADDRESS: 'tflux.2:1606'
      TASKFLUX_GRPC_LISTEN_ADDRESS: 'tflux.2:1607'
      TASKFLUX_TCP_ADAPTER_LISTEN_PORT: 2602
      TASKFLUX_LOG_FILE_SOFT_LIMIT: '33554432'
      TASKFLUX_LOG_FILE_HARD_LIMIT: '67108864'
      TASKFLUX_SNAPSHOT_SNAPSHOT_CREATION_SEGMENTS_THRESHOLD: '5'
    volumes:
      - tflux.2.volume:/var/lib/tflux
    networks:
      - taskflux-network
  
  tflux.3:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    hostname: 'tflux.3'
    ports:
      - '9004:1606'
      - '9005:1607'
    environment:
      TASKFLUX_CLUSTER_PEERS: 'tflux.1:5000 tflux.2:5000 tflux.3:5000'
      TASKFLUX_CLUSTER_NODE_ID: 2
      TASKFLUX_CLUSTER_LISTEN_PORT: 5000
      TASKFLUX_CLUSTER_LISTEN_HOST: tflux.3
      TASKFLUX_CLUSTER_DATA_DIRECTORY: /var/lib/tflux
      TASKFLUX_HTTP_LISTEN_ADDRESS: 'tflux.3:1606'
      TASKFLUX_GRPC_LISTEN_ADDRESS: 'tflux.3:1607'
      TASKFLUX_TCP_ADAPTER_LISTEN_PORT: 2602
      TASKFLUX_LOG_FILE_SOFT_LIMIT: '33554432'
      TASKFLUX_LOG_FILE_HARD_LIMIT: '67108864'
      TASKFLUX_SNAPSHOT_SNAPSHOT_CREATION_SEGMENTS_THRESHOLD: '5'
    volumes:
      - tflux.3.volume:/var/lib/tflux
    networks:
      - taskflux-network

volumes:
  tflux.1.volume:
    driver: local
  tflux.2.volume:
    driver: local
  tflux.3.volume:
    driver: local

networks:
  taskflux-network:
    driver: bridge