services:
  tflux.1:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    hostname: 'tflux.1'
    ports:
      - '9000:2602'
      - '9001:1606'
      - '9002:1607'
    environment:
      TASKFLUX_CLUSTER_PEERS: 'tflux.1:5000'
      TASKFLUX_CLUSTER_NODE_ID: '0'
      TASKFLUX_CLUSTER_LISTEN_PORT: '5000'
      TASKFLUX_CLUSTER_LISTEN_HOST: 'tflux.1'
      TASKFLUX_DATA_DIRECTORY: '/var/lib/tflux'
      TASKFLUX_HTTP_LISTEN_ADDRESS: 'tflux.1:1606'
      TASKFLUX_GRPC_LISTEN_ADDRESS: 'tflux.1:1607'
      TASKFLUX_TCP_ADAPTER_LISTEN_PORT: '2602'
    volumes:
      - tflux.1.volume:/var/lib/tflux

volumes:
  tflux.1.volume:
    driver: local
