services:
  raft.server.1:
    build:
      context: src
      dockerfile: Raft.Server/Dockerfile
    environment:
      PEERS__0__HOST: raft.server.2
      PEERS__0__PORT: 5000
      PEERS__0__ID: 2
      PEERS__1__HOST: raft.server.3
      PEERS__1__PORT: 5000
      PEERS__1__ID: 3
      NODE_ID: 1
      LISTEN_PORT: 5000
      LISTEN_HOST: 0.0.0.0
      
  raft.server.2:
    build:
      context: src
      dockerfile: Raft.Server/Dockerfile
    environment:
      PEERS__0__HOST: raft.server.1
      PEERS__0__PORT: 5000
      PEERS__0__ID: 1
      PEERS__1__HOST: raft.server.3
      PEERS__1__PORT: 5000
      PEERS__1__ID: 3
      NODE_ID: 2
      LISTEN_PORT: 5000
      LISTEN_HOST: 0.0.0.0
      
  raft.server.3:
    build:
      context: src
      dockerfile: Raft.Server/Dockerfile
    environment:
      PEERS__0__HOST: raft.server.1
      PEERS__0__PORT: 5000
      PEERS__0__ID: 1
      PEERS__1__HOST: raft.server.2
      PEERS__1__PORT: 5000
      PEERS__1__ID: 2
      NODE_ID: 3
      LISTEN_PORT: 5000
      LISTEN_HOST: 0.0.0.0
