services:
  tflux.1:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '9000:1606'
    environment:
      PEERS__0: tflux.1:5000
      PEERS__1: tflux.2:5000
      PEERS__2: tflux.3:5000
      NODE_ID: 0
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.1
      HTTP__PORT: 1606
      DATA_DIR: /var/lib/tflux
    volumes:
      - tflux.1.volume:/var/lib/tflux
      
  tflux.2:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '9001:1606'
    environment:
      PEERS__0: tflux.1:5000
      PEERS__1: tflux.2:5000
      PEERS__2: tflux.3:5000
      NODE_ID: 1
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.2
      HTTP__PORT: 1606
      DATA_DIR: /var/lib/tflux
    volumes:
      - tflux.2.volume:/var/lib/tflux
      
  tflux.3:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '9002:1606'
    environment:
      PEERS__0: tflux.1:5000
      PEERS__1: tflux.2:5000
      PEERS__2: tflux.3:5000
      NODE_ID: 2
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.3
      HTTP__PORT: 1606
      DATA_DIR: /var/lib/tflux
    volumes:
      - tflux.3.volume:/var/lib/tflux

volumes:
  tflux.1.volume:
    driver: local
  tflux.2.volume:
    driver: local
  tflux.3.volume:
    driver: local