services:
  raft.server.1:
    build:
      context: src
      dockerfile: Raft.Server/Dockerfile
    environment:
      PEER_HOST: raft.server.2
      PEER_PORT: 5000
      PEER_ID: 2
      NODE_ID: 1
      LISTEN_PORT: 5000
      LISTEN_HOST: 0.0.0.0
      
  raft.server.2:
    build:
      context: src
      dockerfile: Raft.Server/Dockerfile
    environment:
      PEER_HOST: raft.server.1
      PEER_PORT: 5000
      PEER_ID: 1
      NODE_ID: 2
      LISTEN_PORT: 5000
      LISTEN_HOST: 0.0.0.0
