services:
  tflux.1:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '9000:1606'
    environment:
      PEERS__0__HOST: tflux.2
      PEERS__0__PORT: 5000
      PEERS__0__ID: 2
      PEERS__1__HOST: tflux.3
      PEERS__1__PORT: 5000
      PEERS__1__ID: 3
      NODE_ID: 1
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.1
      HTTP__PORT: 1606
    working_dir: /var/lib/tflux
    volumes:
      - tflux.1.volume:/var/lib/tflux
      
  tflux.2:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '9001:1606'
    environment:
      PEERS__0__HOST: tflux.1
      PEERS__0__PORT: 5000
      PEERS__0__ID: 1
      PEERS__1__HOST: tflux.3
      PEERS__1__PORT: 5000
      PEERS__1__ID: 3
      NODE_ID: 2
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.2
      HTTP__PORT: 1606
    working_dir: /var/lib/tflux
    volumes:
      - tflux.2.volume:/var/lib/tflux
      
  tflux.3:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    working_dir: /var/lib/tflux
    ports:
      - '9002:1606'
    environment:
      PEERS__0__HOST: tflux.1
      PEERS__0__PORT: 5000
      PEERS__0__ID: 1
      PEERS__1__HOST: tflux.2
      PEERS__1__PORT: 5000
      PEERS__1__ID: 2
      NODE_ID: 3
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.3
      HTTP__PORT: 1606
    volumes:
      - tflux.3.volume:/var/lib/tflux

volumes:
  tflux.1.volume:
    driver: local
  tflux.2.volume:
    driver: local
  tflux.3.volume:
    driver: local