services:
  raft.server.1:
    build:
      context: src
      dockerfile: Raft.Host/Dockerfile
    ports:
      - '9000:2602'
    environment:
      PEERS__0__HOST: raft.server.2
      PEERS__0__PORT: 5000
      PEERS__0__ID: 2
      PEERS__1__HOST: raft.server.3
      PEERS__1__PORT: 5000
      PEERS__1__ID: 3
      NODE_ID: 1
      LISTEN_PORT: 5000
#      LISTEN_HOST: 0.0.0.0
      LISTEN_HOST: raft.server.1
      HTTP__HOSTNAME_OR_ADDRESS: 12.12.12.12
      HTTP__PORT: 2602
      
  raft.server.2:
    build:
      context: src
      dockerfile: Raft.Host/Dockerfile
    ports:
      - '9001:2602'
    environment:
      PEERS__0__HOST: raft.server.1
      PEERS__0__PORT: 5000
      PEERS__0__ID: 1
      PEERS__1__HOST: raft.server.3
      PEERS__1__PORT: 5000
      PEERS__1__ID: 3
      NODE_ID: 2
      LISTEN_PORT: 5000
#      LISTEN_HOST: 0.0.0.0
      LISTEN_HOST: raft.server.2
      HTTP__HOSTNAME_OR_ADDRESS: 0.0.0.0
      HTTP__PORT: 2602
      
  raft.server.3:
    build:
      context: src
      dockerfile: Raft.Host/Dockerfile
    ports:
      - '9002:2602'
    environment:
      PEERS__0__HOST: raft.server.1
      PEERS__0__PORT: 5000
      PEERS__0__ID: 1
      PEERS__1__HOST: raft.server.2
      PEERS__1__PORT: 5000
      PEERS__1__ID: 2
      NODE_ID: 3
      LISTEN_PORT: 5000
#      LISTEN_HOST: 0.0.0.0
      LISTEN_HOST: raft.server.3
      HTTP__HOSTNAME_OR_ADDRESS: 0.0.0.0
      HTTP__PORT: 2602
  
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on: 
      - prometheus