services:
  tflux.1:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '9000:1606'
    environment:
      TASKFLUX_PEERS: 'tflux.1:5000 tflux.2:5000 tflux.3:5000'
      TASKFLUX_NODE_ID: 0
      TASKFLUX_LISTEN_PORT: 5000
      TASKFLUX_LISTEN_HOST: tflux.1
      TASKFLUX_HTTP_PORT: 1606
      TASKFLUX_DATA_DIR: /var/lib/tflux
    volumes:
      - tflux.1.volume:/var/lib/tflux
      
  tflux.2:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '9001:1606'
    environment:
      TASKFLUX_PEERS: 'tflux.1:5000 tflux.2:5000 tflux.3:5000'
      TASKFLUX_NODE_ID: 1
      TASKFLUX_LISTEN_PORT: 5000
      TASKFLUX_LISTEN_HOST: tflux.2
      TASKFLUX_HTTP_PORT: 1606
      TASKFLUX_DATA_DIR: /var/lib/tflux
    volumes:
      - tflux.2.volume:/var/lib/tflux
      
  tflux.3:
    build:
      context: src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '9002:1606'
    environment:
      TASKFLUX_PEERS: 'tflux.1:5000 tflux.2:5000 tflux.3:5000'
      TASKFLUX_NODE_ID: 2
      TASKFLUX_LISTEN_PORT: 5000
      TASKFLUX_LISTEN_HOST: tflux.3
      TASKFLUX_HTTP_PORT: 1606
      TASKFLUX_DATA_DIR: /var/lib/tflux
    volumes:
      - tflux.3.volume:/var/lib/tflux

volumes:
  tflux.1.volume:
    driver: local
  tflux.2.volume:
    driver: local
  tflux.3.volume:
    driver: local