version: '3.0'

services:
  tflux.1:
    build:
      context: ../../src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '8080:2602'
      - '8081:1606'
    environment:
      PEERS__0: tflux.1:5000
      NODE_ID: 0
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.1
      DATA_DIR:
      HTTP_PORT: 1606
    
  