version: '3.0'

services:
  tflux.0:
    build:
      context: ../../src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '8080:2602'
    environment:
      PEERS__0: tflux.0:5000
      PEERS__1: tflux.1:5000
      PEERS__2: tflux.2:5000
      NODE_ID: 0
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.0
      DATA_DIR:
      HTTP_PORT: 1606
  tflux.1:
    build:
      context: ../../src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '8081:2602'
    environment:
      PEERS__0: tflux.0:5000
      PEERS__1: tflux.1:5000
      PEERS__2: tflux.2:5000
      NODE_ID: 1
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.1
      DATA_DIR:
      HTTP_PORT: 1606
  
  tflux.2:
    build:
      context: ../../src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '8082:2602'
    environment:
      PEERS__0: tflux.0:5000
      PEERS__1: tflux.1:5000
      PEERS__2: tflux.2:5000
      NODE_ID: 2
      LISTEN_PORT: 5000
      LISTEN_HOST: tflux.2
      DATA_DIR:
      HTTP_PORT: 1606
    
  