version: '3.0'

services:
  tflux.1:
    build:
      context: ../../src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '8080:2602'
      - '8081:1606'
    environment:
      TASKFLUX_CLUSTER_PEERS: 'tflux.0:5000'
      TASKFLUX_CLUSTER_NODE_ID: 0
      TASKFLUX_CLUSTER_LISTEN_PORT: 5000
      TASKFLUX_CLUSTER_LISTEN_HOST: tflux.0
      TASKFLUX_CLUSTER_DATA_DIRECTORY: '/var/lib/tflux'
      TASKFLUX_HTTP_ADAPTER_LISTEN_PORT: 1606
      TASKFLUX_TCP_ADAPTER_LISTEN_PORT: 2606
    
  