version: '3.0'

services:
  tflux.1:
    build:
      context: ../../src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '8080:2602'
      - '8081:1606'
    environment:
      TASKFLUX_PEERS: tflux.1:5000
      TASKFLUX_NODE_ID: 0
      TASKFLUX_LISTEN_PORT: 5000
      TASKFLUX_LISTEN_HOST: tflux.1
      TASKFLUX_DATA_DIR:
      TASKFLUX_HTTP_PORT: 1606
    
  