version: '3.0'

services:
  tflux.0:
    build:
      context: ../../src
      dockerfile: TaskFlux.Host/Dockerfile
    ports:
      - '8080:2602'
      - '8081:1606'
      - '8082:1607'
    environment:
      TASKFLUX_CLUSTER_PEERS: 'tflux.0:5000'
      TASKFLUX_CLUSTER_NODE_ID: 0
      TASKFLUX_CLUSTER_LISTEN_PORT: 5000
      TASKFLUX_CLUSTER_LISTEN_HOST: tflux.0
      TASKFLUX_DATA_DIRECTORY: '/var/lib/tflux'
      TASKFLUX_HTTP_LISTEN_ADDRESS: 'tflux.0:1606'
      TASKFLUX_GRPC_LISTEN_ADDRESS: 'tflux.0:1607'
      TASKFLUX_TCP_ADAPTER_LISTEN_PORT: 2602
      TASKFLUX_LOG_LEVEL: 'Debug'
      TASKFLUX_MAX_LOG_FILE_SIZE: 1024
    
  